In [1]:
import pandas as pd

In [5]:
data = pd.read_csv('cleaned_data')
data.head()

,Unnamed: 0,description,duration,months_ago,ted_types,top_rating,total_views
0,0,Sir Ken Robinson makes an entertaining and pro...,1164,150,TED,Inspiring,47227110
1,1,With the same humor and humanity he exuded in ...,977,150,TED,Funny,3200520
2,2,New York Times columnist David Pogue takes aim...,1286,150,TED,Funny,1636292
3,3,"In an emotionally charged talk, MacArthur-winn...",1116,150,TED,Inspiring,1697550
4,4,You've never seen data presented like this. Wi...,1190,150,TED,Informative,12005869

In [8]:
a = data['ted_types']

In [17]:
cat_rating= a.astype('category')
onedummycolumn = cat_rating.cat.codes
dummyted = pd.get_dummies(cat_rating)

In [18]:
b = data['top_rating']

In [19]:
cat_rating= b.astype('category')
onedummycolumn = cat_rating.cat.codes
dummyrating = pd.get_dummies(cat_rating)

In [22]:
newdata = pd.concat([data, dummyted, dummyrating], axis=1)

In [30]:
pd.set_option('display.max_columns', 100)

In [78]:
realdata = newdata.drop(['Unnamed: 0', 'ted_types', 'top_rating', 'description'], 1)
realrealdata = realdata.rename(columns={'Other TED': 'Other_TED', 'Jaw-dropping': 'Jaw_dropping'})
realrealdata.head()

,duration,months_ago,total_views,Other_TED,TED,TEDGlobal,TEDMED,TEDSalon,TEDWomen,TEDx,Beautiful,Confusing,Courageous,Fascinating,Funny,Informative,Ingenious,Inspiring,Jaw_dropping,Longwinded,OK,Obnoxious,Persuasive,Unconvincing
0,1164,150,47227110,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,977,150,3200520,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,1286,150,1636292,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
3,1116,150,1697550,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
4,1190,150,12005869,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0

In [81]:
realrealdata['views'] = realrealdata['total_views']
momma = realrealdata.drop(columns = 'total_views')
momma

,duration,months_ago,Other_TED,TED,TEDGlobal,TEDMED,TEDSalon,TEDWomen,TEDx,Beautiful,Confusing,Courageous,Fascinating,Funny,Informative,Ingenious,Inspiring,Jaw_dropping,Longwinded,OK,Obnoxious,Persuasive,Unconvincing,views
0,1164,150,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,47227110
1,977,150,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,3200520
2,1286,150,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1636292
3,1116,150,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1697550
4,1190,150,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,12005869
5,1305,150,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,20685401
6,992,151,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,3769987
7,1198,151,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,967741
8,1485,151,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2567958
9,1262,151,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,3095993
10,1414,151,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1211416
11,1538,151,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,387877
12,1550,151,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,693341
13,527,151,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,4531020
14,1057,151,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,358304
15,1481,152,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,2702470
16,1445,152,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1628912
17,906,152,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1415724
18,1170,152,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1074081
19,1201,152,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1106561
20,1114,152,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,966439
21,1136,152,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,6141440
22,1006,152,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,518624
23,1407,153,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,9260764
24,1225,153,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1131864
25,1140,153,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1096862
26,1316,153,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,2885999
27,1275,153,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2863214
28,1050,153,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,7023562
29,1276,153,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,14689301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2520,736,20,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,840855
2521,685,20,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,727807
2522,530,20,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,636463
2523,747,20,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,744793
2524,310,20,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,522917
2525,791,20,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,656113
2526,817,20,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,773317
2527,865,20,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,766721
2528,717,20,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,539207
2529,1156,21,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,857850
2530,738,21,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,591131
2531,698,21,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,665328
2532,993,21,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1070238
2533,663,21,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,248411
2534,725,21,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,646174
2535,723,21,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,707788
2536,865,21,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,566101
2537,738,21,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1009069
2538,808,21,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,621431
2539,934,21,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,527314
2540,722,21,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,613915
2541,957,21,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,656791
2542,795,21,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,542088
2543,894,21,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,534824
2544,810,21,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,418368
2545,476,21,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,450430
2546,290,21,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,417470
2547,651,21,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,375647
2548,1100,21,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,419309
2549,519,21,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,391721

In [50]:
from statsmodels.formula.api import ols
import statsmodels.api as sm

In [67]:
outcome = 'total_views'
predictors = realrealdata.drop('total_views', axis=1)
pred_sum = "+".join(predictors.columns)
formula = outcome + "~" + pred_sum

In [68]:
model = ols(formula= formula, data= realrealdata).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            total_views   R-squared:                       0.041
Model:                            OLS   Adj. R-squared:                  0.033
Method:                 Least Squares   F-statistic:                     5.197
Date:                Wed, 05 Dec 2018   Prob (F-statistic):           1.48e-13
Time:                        16:07:19   Log-Likelihood:                -41128.
No. Observations:                2550   AIC:                         8.230e+04
Df Residuals:                    2528   BIC:                         8.243e+04
Df Model:                          21
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     9.301e+05   2.03e+05      4.573      0.000    5.31e+05    1.33e+06
duration       288.1571    136.093      2.117      0.034      21.292     555.022
months_ago   -1392.6020   1459.629     -0.954      0.340   -4254.793    1469.590
Other_TED    -1.809e+05   1.32e+05     -1.372      0.170   -4.39e+05    7.76e+04
TED            4.38e+05   1.01e+05      4.337      0.000     2.4e+05    6.36e+05
TEDGlobal     3.709e+05   1.26e+05      2.951      0.003    1.24e+05    6.17e+05
TEDMED        7.763e+04   2.67e+05      0.290      0.771   -4.46e+05    6.02e+05
TEDSalon      2.265e+05   2.12e+05      1.066      0.286    -1.9e+05    6.43e+05
TEDWomen     -1.277e+05   2.29e+05     -0.557      0.577   -5.77e+05    3.22e+05
TEDx          1.257e+05    1.2e+05      1.050      0.294   -1.09e+05     3.6e+05
Beautiful    -1.666e+05   2.56e+05     -0.652      0.514   -6.68e+05    3.34e+05
Confusing    -8.925e+05   1.63e+06     -0.549      0.583   -4.08e+06     2.3e+06
Courageous    6.003e+05   3.07e+05      1.955      0.051   -1723.265     1.2e+06
Fascinating   4.472e+05   2.26e+05      1.976      0.048    3323.340    8.91e+05
Funny         9.074e+05   2.51e+05      3.614      0.000    4.15e+05     1.4e+06
Informative    1.13e+05   1.98e+05      0.571      0.568   -2.75e+05    5.01e+05
Ingenious    -2.704e+05   2.87e+05     -0.942      0.346   -8.33e+05    2.92e+05
Inspiring     6.762e+05   1.94e+05      3.482      0.001    2.95e+05    1.06e+06
Jaw_dropping  2.167e+06   3.62e+05      5.993      0.000    1.46e+06    2.88e+06
Longwinded    -1.02e+06   8.32e+05     -1.225      0.221   -2.65e+06    6.12e+05
OK           -3.111e+05   8.85e+05     -0.352      0.725   -2.05e+06    1.42e+06
Obnoxious    -7.472e+05   1.16e+06     -0.646      0.519   -3.02e+06    1.52e+06
Persuasive   -2.048e+05   3.09e+05     -0.663      0.508   -8.11e+05    4.01e+05
Unconvincing -3.684e+05   5.08e+05     -0.725      0.469   -1.37e+06    6.28e+05
==============================================================================
Omnibus:                     3660.808   Durbin-Watson:                   1.777
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1280174.060
Skew:                           8.380   Prob(JB):                         0.00
Kurtosis:                     111.479   Cond. No.                     1.24e+19
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.38e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [75]:
from sklearn import svm
from sklearn.datasets import samples_generator
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

print(__doc__)

Automatically created module for IPython interactive environment

In [82]:
X = momma.iloc[:, :-1]
y = momma['views']

In [87]:
# import some data to play with
X, y = samples_generator.make_classification()

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# ANOVA SVM-C
# 1) anova filter, take 3 best ranked features
anova_filter = SelectKBest(f_regression, k=6)
# 2) svm
clf = svm.SVC(kernel='linear')

anova_svm = make_pipeline(anova_filter, clf)
anova_svm.fit(X_train, y_train)
y_pred = anova_svm.predict(X_test)
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.79      1.00      0.88        11
          1       1.00      0.79      0.88        14

avg / total       0.91      0.88      0.88        25

In [84]:
X

array([[-2.20583859,  1.16200709, -0.26452074, ...,  0.58868639,
         0.627962  , -0.53936317],
       [-0.23720345, -0.1923038 , -1.01765563, ...,  0.82998025,
        -0.38575639,  0.28208505],
       [-0.15556082, -0.84008793, -1.39370546, ...,  0.51486701,
        -0.11545716,  0.70612792],
       ...,
       [-0.5884119 , -1.06801977,  1.13067472, ...,  0.35956142,
        -0.85356561, -0.28071379],
       [-0.50239041, -0.33807875,  1.43665833, ..., -0.75105101,
        -0.56526229, -0.54920699],
       [-2.39045728, -0.77256395,  2.23537673, ..., -0.13286055,
        -0.28413204, -1.42115719]])

In [93]:
formula = "views ~ Jaw_dropping"
model = ols(formula = formula, data = momma).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  views   R-squared:                       0.011
Model:                            OLS   Adj. R-squared:                  0.011
Method:                 Least Squares   F-statistic:                     29.62
Date:                Wed, 05 Dec 2018   Prob (F-statistic):           5.75e-08
Time:                        17:08:26   Log-Likelihood:                -41168.
No. Observations:                2550   AIC:                         8.234e+04
Df Residuals:                    2548   BIC:                         8.235e+04
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     1.659e+06   4.97e+04     33.372      0.000    1.56e+06    1.76e+06
Jaw_dropping  1.877e+06   3.45e+05      5.443      0.000     1.2e+06    2.55e+06
==============================================================================
Omnibus:                     3656.256   Durbin-Watson:                   1.770
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1252461.418
Skew:                           8.369   Prob(JB):                         0.00
Kurtosis:                     110.274   Cond. No.                         7.01
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [94]:
momma['views'].quantile(.99)

12023264.589999992

In [112]:
momma.sort_values('views')
daddy = momma[(momma['views']>200000) & (momma['views']<10000000)]
sister = daddy.sort_values('views')

In [115]:
outcome = 'views'
predictors = sister.drop('views', axis=1)
pred_sum = "+".join(predictors.columns)
formula = outcome + "~" + pred_sum

In [116]:
model = ols(formula= formula, data= sister).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  views   R-squared:                       0.076
Model:                            OLS   Adj. R-squared:                  0.069
Method:                 Least Squares   F-statistic:                     9.711
Date:                Wed, 05 Dec 2018   Prob (F-statistic):           1.64e-30
Time:                        17:24:58   Log-Likelihood:                -38383.
No. Observations:                2484   AIC:                         7.681e+04
Df Residuals:                    2462   BIC:                         7.694e+04
Df Model:                          21
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     1.167e+06   1.04e+05     11.193      0.000    9.62e+05    1.37e+06
duration        92.4879     70.647      1.309      0.191     -46.046     231.022
months_ago   -4039.1687    752.992     -5.364      0.000   -5515.732   -2562.606
Other_TED    -2.515e+04   6.79e+04     -0.371      0.711   -1.58e+05    1.08e+05
TED           4.409e+05   5.18e+04      8.513      0.000    3.39e+05    5.42e+05
TEDGlobal     2.286e+05   6.47e+04      3.533      0.000    1.02e+05    3.55e+05
TEDMED          4.1e+04   1.37e+05      0.299      0.765   -2.27e+05    3.09e+05
TEDSalon      3.158e+05   1.09e+05      2.898      0.004    1.02e+05    5.29e+05
TEDWomen       7.07e+04   1.17e+05      0.606      0.544   -1.58e+05    2.99e+05
TEDx          9.491e+04   6.21e+04      1.528      0.127   -2.69e+04    2.17e+05
Beautiful     -5.82e+04    1.3e+05     -0.446      0.656   -3.14e+05    1.98e+05
Confusing    -6.408e+05   8.27e+05     -0.775      0.439   -2.26e+06    9.81e+05
Courageous    3.867e+05   1.58e+05      2.446      0.015    7.67e+04    6.97e+05
Fascinating   4.446e+05   1.16e+05      3.841      0.000    2.18e+05    6.72e+05
Funny         7.135e+05   1.28e+05      5.559      0.000    4.62e+05    9.65e+05
Informative    1.29e+05   1.01e+05      1.278      0.201   -6.89e+04    3.27e+05
Ingenious    -1.185e+05   1.46e+05     -0.809      0.419   -4.06e+05    1.69e+05
Inspiring     4.703e+05   9.92e+04      4.741      0.000    2.76e+05    6.65e+05
Jaw_dropping  1.555e+06    1.9e+05      8.201      0.000    1.18e+06    1.93e+06
Longwinded   -6.886e+05   4.23e+05     -1.627      0.104   -1.52e+06    1.41e+05
OK           -2.616e+05    4.5e+05     -0.582      0.561   -1.14e+06     6.2e+05
Obnoxious    -5.809e+05   5.88e+05     -0.987      0.324   -1.73e+06    5.73e+05
Persuasive    5.463e+04   1.58e+05      0.345      0.730   -2.56e+05    3.65e+05
Unconvincing -2.382e+05   2.58e+05     -0.922      0.357   -7.45e+05    2.69e+05
==============================================================================
Omnibus:                     1539.373   Durbin-Watson:                   0.139
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            15572.073
Skew:                           2.850   Prob(JB):                         0.00
Kurtosis:                      13.861   Cond. No.                     1.34e+19
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.14e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""